### PR TITLE
Remove unwanted quotes in action output on Windows

### LINKED ISSUE #23: How to delete quotes when tag message has Multiple lines
Hi, thank you for your project, it's helpful ! And I have a little question.

My action yml below:

```yaml

......

- name: Get tag message
      id: tag_data
      uses: ericcornelissen/git-tag-annotation-action@v1

......

- name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        release_name: "${{ env.RELEASE_TITLE }}"
        body: |
          ${{ steps.tag_data.outputs.git-tag-annotation }}
```

Then I found the release body has quotes at the beginning and ending. How to delete it ?

XBSJ(KN$51N(TSI)DEW61LK

The whole yml file is at https://github.com/miyouzi/aniGamerPlus/blob/master/.github/workflows/Release-build.yml

### PR DESCRIPTION
**Pull request by ericcornelissen**
Closes #23

### CODE REVIEW

**Comment by ericcornelissen** [comment]
@miyouzi, to be sure this fixes the issue, could you try this out by using this branch in your workflow?

```diff
    - name: Get tag message
      id: tag_data
-     uses: ericcornelissen/git-tag-annotation-action@v1
+     uses: ericcornelissen/git-tag-annotation-action@bug-23/quotes-with-windows
```

**Comment by miyouzi** [comment]
I have tried. It seems have some problems

image

Action output: https://github.com/miyouzi/aniGamerPlus/runs/3208708430

Commit here: https://github.com/miyouzi/aniGamerPlus/commit/8bc78dd199cc3a7d37e89b2c5bec6cd9945e57ad

**Comment by ericcornelissen** [comment]
Ah yes, forgot to point this out :sweat_smile: Because of the way `run:` values are parsed you need to change your "Test ENV" step to **include** quotes when `echo`ing this action's output. If you don't do that it thinks the lines in the commit message are supposed to be commands.

```diff
    - name: Test ENV
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
        echo $RELEASE_TITLE
        echo ${{ env.RELEASE_TITLE }}
        echo $RELEASE_FILENAME
        echo ${{ env.RELEASE_FILENAME }}
        echo $TAG_MESSAGE
-       echo ${{ steps.tag_data.outputs.git-tag-annotation }}
+       echo '${{ steps.tag_data.outputs.git-tag-annotation }}'
```

**Comment by miyouzi** [comment]
Great ! It works well now ! Thank you very much ! ❤

**Comment by ericcornelissen** [comment]
And thank you for verifying the fix and initially reporting the bug!

I'll merge this now and release a new version. You can switch back to `v1` as shown below once that is done :slightly_smiling_face: 

```diff
    - name: Get tag message
      id: tag_data
-     uses: ericcornelissen/git-tag-annotation-action@bug-23/quotes-with-windows
+     uses: ericcornelissen/git-tag-annotation-action@v1
```

**Comment by miyouzi** [comment]
> 并感谢您验证修复并最初报告错误！
> 
> 我现在将合并它并发布一个新版本。可以切换回`v1`如下图~一旦完成~ 现在 🙂
> 
> ```diff
>     - 名称：获取标签消息
>       id：标签数据
> -     使用：ericcornelissen/git-tag-annotation-action@bug-23/quotes-with-windows 
> +     使用：ericcornelissen/git-tag-annotation-action@v1
> ```

OK. Thank you !

**Pull request merged**
